// from-figma/CostsTab.tsx
import {
	DollarSign,
	Plus,
	Trash2,
	TrendingDown,
	TrendingUp,
	Users,
} from "lucide-react";
import React, { useEffect, useState } from "react";
import { costTrackerApi } from "../src/services/api.ts";
import { Badge } from "../ui/badge";
import { Button } from "../ui/button";
import {
	Card,
	CardContent,
	CardDescription,
	CardHeader,
	CardTitle,
} from "../ui/card";
import { Checkbox } from "../ui/checkbox";
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogHeader,
	DialogTitle,
	DialogTrigger,
} from "../ui/dialog";
import { Input } from "../ui/input";
import { Label } from "../ui/label";
import {
	Select,
	SelectContent,
	SelectItem,
	SelectTrigger,
	SelectValue,
} from "../ui/select";

interface CostsTabProps {
  tripId: string;
  trip: any;
}

export function CostsTab({ tripId, trip }: CostsTabProps) {
  const [costs, setCosts] = useState<any[]>([]);
  const [balances, setBalances] = useState<any>({});
  const [isAddDialogOpen, setIsAddDialogOpen] = useState(false);
  const [newCost, setNewCost] = useState({
    description: '',
    amount: '',
    paidBy: '',
    splitAmong: [] as string[]
  });

  useEffect(() => {
    loadCosts();
  }, [tripId]);

  const loadCosts = async () => {
    try {
      // Load expenses from API
      const [percentageExpenses, moneyExpenses] = await Promise.all([
        costTrackerApi.listPercentageExpenses(),
        costTrackerApi.listMoneyExpenses(),
      ]);
      
      // Combine and transform expenses
      const allExpenses = [
        ...percentageExpenses.listedExpenses.map(exp => ({ ...exp, type: 'percentage' })),
        ...moneyExpenses.listedExpenses.map(exp => ({ ...exp, type: 'money' })),
      ];
      
      setCosts(allExpenses);
      
      // Calculate balances from expenses
      // This is a simplified calculation - you may want to enhance this
      const balances: Record<string, number> = {};
      // TODO: Implement proper balance calculation from expense details
      setBalances(balances);
    } catch (error) {
      console.error('Error loading costs:', error);
      setCosts([]);
    }
  };

  const getAvatarColor = (index: number) => {
    const colors = ['#14b8a6', '#ff7b6b', '#7ba3d1', '#f4c542', '#8ba888'];
    return colors[index % colors.length];
  };

  const handleAddCost = async (e: React.FormEvent) => {
    e.preventDefault();
    // Demo mode - show message
    console.log('Demo version: Adding costs is not available yet');
    setIsAddDialogOpen(false);
  };

  const handleDeleteCost = async (costId: string) => {
    // Demo mode - show message
    console.log('Demo version: Deleting costs is not available yet');
  };

  const handleSplitToggle = (memberId: string, checked: boolean) => {
    if (checked) {
      setNewCost({
        ...newCost,
        splitAmong: [...newCost.splitAmong, memberId]
      });
    } else {
      setNewCost({
        ...newCost,
        splitAmong: newCost.splitAmong.filter(id => id !== memberId)
      });
    }
  };

  const getMemberName = (memberId: string) => {
    return trip.members.find((m: any) => m.id === memberId)?.name || 'Unknown';
  };

  const formatCurrency = (amount: number) => {
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD'
    }).format(amount);
  };

  return (
    <div className="space-y-6">
      <Card className="rounded-2xl border-0 shadow-md overflow-hidden">
        <div className="h-1.5 bg-[#f4c542]" />
        <CardHeader>
          <div className="flex justify-between items-center">
            <div>
              <CardTitle className="text-[#1e3a5f]">Trip Expenses</CardTitle>
              <CardDescription>Track costs and split them among the group</CardDescription>
            </div>
            <div className="flex items-center gap-2">
              <Dialog>
                <DialogTrigger asChild>
                  <Button className="bg-[#f4c542] hover:bg-[#e0b138] hover:shadow-lg hover:scale-105 transition-all rounded-full">
                    <Plus className="mr-2 size-4" />
                    Add Expense
                  </Button>
                </DialogTrigger>
                <DialogContent>
                  <DialogHeader>
                    <DialogTitle className="text-[#1e3a5f]">Add Expense</DialogTitle>
                    <DialogDescription>
                      Record a trip expense and split it among members
                    </DialogDescription>
                  </DialogHeader>
                  <form onSubmit={handleAddCost} className="space-y-4">
                    <div className="space-y-2">
                      <Label htmlFor="description">Description</Label>
                      <Input
                        id="description"
                        placeholder="e.g., Airbnb for 3 nights"
                        value={newCost.description}
                        onChange={(e) => setNewCost({ ...newCost, description: e.target.value })}
                        required
                      />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="amount">Total Amount ($)</Label>
                      <Input
                        id="amount"
                        type="number"
                        step="0.01"
                        placeholder="0.00"
                        value={newCost.amount}
                        onChange={(e) => setNewCost({ ...newCost, amount: e.target.value })}
                        required
                      />
                    </div>

                    <div className="space-y-2">
                      <Label htmlFor="paidBy">Paid By</Label>
                      <Select value={newCost.paidBy} onValueChange={(value) => setNewCost({ ...newCost, paidBy: value })}>
                        <SelectTrigger>
                          <SelectValue placeholder="Select member" />
                        </SelectTrigger>
                        <SelectContent>
                          {trip.members.map((member: any) => (
                            <SelectItem key={member.id} value={member.id}>
                              {member.name}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                    </div>

                    <div className="space-y-2">
                      <Label>Split Among</Label>
                      <div className="space-y-2 border rounded-md p-3">
                        {trip.members.map((member: any) => (
                          <div key={member.id} className="flex items-center space-x-2">
                            <Checkbox
                              id={`split-${member.id}`}
                              checked={newCost.splitAmong.includes(member.id)}
                              onCheckedChange={(checked) => handleSplitToggle(member.id, checked === true)}
                            />
                            <label htmlFor={`split-${member.id}`} className="text-sm cursor-pointer">
                              {member.name}
                            </label>
                          </div>
                        ))}
                      </div>
                    </div>

                    <Button type="submit" className="w-full">Add Expense</Button>
                  </form>
                </DialogContent>
              </Dialog>
            </div>
          </div>
        </CardHeader>
      </Card>

      <div className="grid gap-6 md:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle>Member Balances</CardTitle>
            <CardDescription>Who owes and who's owed</CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {trip.members.map((member: any, index: number) => {
              const balance = balances[member.id] || 0;
              const isPositive = balance > 0;
              const isZero = Math.abs(balance) < 0.01;

              return (
                <div key={member.id} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                  <div className="flex items-center gap-3">
                    <div 
                      className="size-10 rounded-full flex items-center justify-center text-white"
                      style={{ backgroundColor: getAvatarColor(index) }}
                    >
                      {member.name.charAt(0).toUpperCase()}
                    </div>
                    <div>
                      <p>{member.name}</p>
                    </div>
                  </div>
                  <div className="text-right">
                    {isZero ? (
                      <Badge variant="secondary">Settled</Badge>
                    ) : (
                      <div className={`flex items-center gap-1 ${isPositive ? 'text-green-600' : 'text-red-600'}`}>
                        {isPositive ? <TrendingUp className="size-4" /> : <TrendingDown className="size-4" />}
                        <span>{formatCurrency(Math.abs(balance))}</span>
                      </div>
                    )}
                  </div>
                </div>
              );
            })}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Recent Expenses</CardTitle>
            <CardDescription>All trip expenses</CardDescription>
          </CardHeader>
          <CardContent>
            {costs.length === 0 ? (
              <p className="text-center text-gray-500 py-8">No expenses yet</p>
            ) : (
              <div className="space-y-3">
                {costs.map((cost) => (
                  <div key={cost.id} className="flex items-start justify-between p-3 bg-gray-50 rounded-lg group">
                    <div className="flex-1">
                      <div className="flex items-center gap-2">
                        <DollarSign className="size-4 text-green-600" />
                        <p>{cost.description}</p>
                      </div>
                      <p className="text-sm text-gray-500 mt-1">
                        Paid by {getMemberName(cost.paidBy)} · Split {cost.splitAmong.length} ways
                      </p>
                      <p className="text-xs text-gray-400 mt-1">
                        {formatCurrency(cost.amount / cost.splitAmong.length)} per person
                      </p>
                    </div>
                    <div className="flex items-center gap-2">
                      <span className="text-lg">{formatCurrency(cost.amount)}</span>
                      <Button
                        variant="ghost"
                        size="sm"
                        className="opacity-0 group-hover:opacity-100 transition-opacity"
                        onClick={() => handleDeleteCost(cost.id)}
                      >
                        <Trash2 className="size-4 text-red-500" />
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

// src/components/tabs/CostsTab.vue
<template>
  <div class="costs-tab">
    <div class="space-y-6">
      <!-- Trip Expenses Card -->
      <div class="card">
        <div class="card-gradient-gold"></div>
        <div class="card-header">
          <div>
            <h2 class="card-title">Trip Expenses</h2>
            <p class="card-description">Track costs and split them among the group</p>
          </div>
          <button class="btn-add-expense" @click="showAddExpenseDialog = true">
            <svg class="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 4v16m8-8H4" />
            </svg>
            Add Expense
          </button>
        </div>
      </div>

      <div class="costs-grid">
        <!-- Member Balances -->
        <div class="card">
          <div class="card-header">
            <h2 class="card-title">Member Balances</h2>
            <p class="card-description">Who owes and who's owed</p>
          </div>
          <div class="card-content">
            <div class="balances-list">
              <div
                v-for="(balance, index) in memberBalances"
                :key="balance.travelerId"
                class="balance-item"
                :class="{ positive: balance.balance > 0, negative: balance.balance < 0, zero: Math.abs(balance.balance) < 0.01 }"
              >
                <div class="balance-avatar" :style="{ backgroundColor: getAvatarColor(index) }">
                  {{ getTravelerName(balance.travelerId).charAt(0).toUpperCase() }}
                </div>
                <div class="balance-info">
                  <p class="balance-name">{{ getTravelerName(balance.travelerId) }}</p>
                </div>
                <div class="balance-amount-wrapper">
                  <span v-if="Math.abs(balance.balance) < 0.01" class="badge-settled">Settled</span>
                  <div v-else class="balance-amount" :class="{ positive: balance.balance > 0, negative: balance.balance < 0 }">
                    <svg v-if="balance.balance > 0" class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 7h8m0 0v8m0-8l-8 8-4-4-6 6" />
                    </svg>
                    <svg v-else class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 17h8m0 0V9m0 8l-8-8-4 4-6-6" />
                    </svg>
                    <span>{{ formatBalance(Math.abs(balance.balance)) }}</span>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        <!-- Recent Expenses -->
        <div class="card">
          <div class="card-header">
            <h2 class="card-title">Recent Expenses</h2>
            <p class="card-description">All trip expenses</p>
          </div>
          <div class="card-content">
            <div class="expenses-list">
              <div v-if="expenses.length === 0" class="empty-state">
                <p>No expenses yet</p>
              </div>
              <div
                v-for="expense in expenses"
                :key="expense.id"
                class="expense-item"
              >
                <div class="expense-info">
                  <div class="expense-header">
                    <svg class="w-4 h-4 text-green-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
                    </svg>
                    <h3>{{ expense.title }}</h3>
                  </div>
                  <p class="expense-details">
                    Paid by {{ getTravelerName(expense.paidBy) }} · Split {{ expense.splitBetween.length }} ways
                  </p>
                  <p class="expense-per-person">
                    {{ formatCurrency(expense.totalCost / expense.splitBetween.length) }} per person
                  </p>
                </div>
                <div class="expense-amount-wrapper">
                  <span class="expense-amount">{{ formatCurrency(expense.totalCost) }}</span>
                  <button class="btn-delete-expense" @click="handleDeleteExpense(expense.id)">
                    <svg class="w-4 h-4 text-red-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M19 7l-.867 12.142A2 2 0 0116.138 21H7.862a2 2 0 01-1.995-1.858L5 7m5 4v6m4-6v6m1-10V4a1 1 0 00-1-1h-4a1 1 0 00-1 1v3M4 7h16" />
                    </svg>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Add Expense Dialog -->
    <div v-if="showAddExpenseDialog" class="dialog-overlay" @click="showAddExpenseDialog = false">
      <div class="dialog" @click.stop>
        <h2>Add Expense</h2>
        <form @submit.prevent="addExpense">
          <div class="form-group">
            <label>Title</label>
            <input v-model="newExpense.title" type="text" required placeholder="e.g., Dinner at Joe's" />
          </div>
          <div class="form-group">
            <label>Total Amount</label>
            <input v-model.number="newExpense.totalCost" type="number" step="0.01" required placeholder="0.00" />
          </div>
          <div class="form-group">
            <label>Split Type</label>
            <select v-model="newExpense.splitType">
              <option value="money">Money-based (exact amounts)</option>
              <option value="percentage">Percentage-based</option>
            </select>
          </div>
          <div class="form-group">
            <label>Paid By</label>
            <select v-model="newExpense.paidBy" required>
              <option v-for="traveler in travelers" :key="traveler.id" :value="traveler.id">
                {{ traveler.name }}
              </option>
            </select>
          </div>
          <div class="form-group">
            <label>Split Between</label>
            <div class="checkbox-group">
              <label v-for="traveler in travelers" :key="traveler.id" class="checkbox-label">
                <input
                  type="checkbox"
                  :value="traveler.id"
                  v-model="newExpense.splitBetween"
                />
                {{ traveler.name }}
              </label>
            </div>
          </div>

          <!-- Advanced Settings Toggle -->
          <div class="form-group">
            <button
              type="button"
              class="btn-link"
              @click="showAdvancedSettings = !showAdvancedSettings"
            >
              {{ showAdvancedSettings ? '▼' : '▶' }} Advanced Settings
            </button>
          </div>

          <!-- Advanced Settings -->
          <div v-if="showAdvancedSettings" class="advanced-settings">
            <div class="form-group">
              <label>Custom Split Amounts</label>
              <p class="help-text">
                <span v-if="newExpense.splitType === 'money'">
                  Enter exact amounts for each person. Total must equal ${{ newExpense.totalCost.toFixed(2) }}
                </span>
                <span v-else>
                  Enter percentages for each person. Total must equal 100%
                </span>
              </p>
              <div class="custom-splits">
                <div
                  v-for="travelerId in newExpense.splitBetween"
                  :key="travelerId"
                  class="custom-split-item"
                >
                  <label class="split-label">
                    {{ getTravelerName(travelerId) }}
                    <span v-if="newExpense.splitType === 'money'">($)</span>
                    <span v-else>(%)</span>
                  </label>
                  <input
                    v-model.number="customSplits[travelerId]"
                    type="number"
                    :step="newExpense.splitType === 'money' ? '0.01' : '0.1'"
                    :placeholder="newExpense.splitType === 'money' ? '0.00' : '0'"
                    class="split-input"
                    @input="validateSplits"
                  />
                </div>
              </div>
              <div v-if="splitError" class="error-message">
                {{ splitError }}
              </div>
              <div v-if="splitTotal" class="split-total">
                Total: 
                <span :class="{ valid: isSplitValid, invalid: !isSplitValid }">
                  {{ splitTotal }}
                  <span v-if="newExpense.splitType === 'money'">$</span>
                  <span v-else>%</span>
                </span>
              </div>
            </div>
          </div>

          <div class="form-actions">
            <button type="button" class="btn-secondary" @click="showAddExpenseDialog = false">
              Cancel
            </button>
            <button type="submit" class="btn-primary" :disabled="!canSubmit">Add Expense</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue';
import type { Expense, Traveler, MemberBalance } from '../../types/trip';

const props = defineProps<{
  expenses: Expense[];
  travelers: Traveler[];
}>();

const emit = defineEmits<{
  (e: 'add-expense', expense: Expense): void;
}>();

const showAddExpenseDialog = ref(false);
const showAdvancedSettings = ref(false);
const customSplits = ref<Record<string, number>>({});
const splitError = ref('');
const newExpense = ref({
  title: '',
  totalCost: 0,
  paidBy: '',
  splitBetween: [] as string[],
  splitType: 'money' as 'money' | 'percentage',
});

const memberBalances = computed<MemberBalance[]>(() => {
  const balances: Record<string, number> = {};
  
  // Initialize all travelers with 0 balance
  props.travelers.forEach(t => {
    balances[t.id] = 0;
  });

  // Calculate balances from expenses
  props.expenses.forEach(expense => {
    // Person who paid gets positive balance (owed money)
    balances[expense.paidBy] = (balances[expense.paidBy] || 0) + expense.totalCost;
    
    // People who split get negative balance (owe money)
    expense.splitBetween.forEach(splitUser => {
      const cost = splitUser.cost || 0;
      balances[splitUser.userId] = (balances[splitUser.userId] || 0) - cost;
    });
  });

  return Object.entries(balances).map(([travelerId, balance]) => ({
    travelerId,
    balance,
  }));
});

function getTravelerName(travelerId: string): string {
  return props.travelers.find(t => t.id === travelerId)?.name || 'Unknown';
}

function formatBalance(balance: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD'
  }).format(balance);
}

function formatCurrency(amount: number): string {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD'
  }).format(amount);
}

function getAvatarColor(index: number): string {
  const colors = ['#14b8a6', '#ff7b6b', '#7ba3d1', '#f4c542', '#8ba888'];
  return colors[index % colors.length];
}

function handleDeleteExpense(expenseId: string) {
  // This would call the API to delete the expense
  console.log('Delete expense:', expenseId);
}

function formatDate(dateString: string): string {
  const date = new Date(dateString);
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric' });
}

const splitTotal = computed(() => {
  if (!showAdvancedSettings.value || newExpense.value.splitBetween.length === 0) {
    return null;
  }
  const total = newExpense.value.splitBetween.reduce((sum, id) => {
    return sum + (customSplits.value[id] || 0);
  }, 0);
  return total.toFixed(2);
});

const isSplitValid = computed(() => {
  if (!showAdvancedSettings.value || newExpense.value.splitBetween.length === 0) {
    return true; // Valid if not using advanced settings
  }
  const total = parseFloat(splitTotal.value || '0');
  if (newExpense.value.splitType === 'money') {
    return Math.abs(total - newExpense.value.totalCost) < 0.01;
  } else {
    return Math.abs(total - 100) < 0.1;
  }
});

const canSubmit = computed(() => {
  if (newExpense.value.splitBetween.length === 0) return false;
  if (showAdvancedSettings.value) {
    return isSplitValid.value && !splitError.value;
  }
  return true;
});

function validateSplits() {
  splitError.value = '';
  if (!showAdvancedSettings.value) return;

  const total = parseFloat(splitTotal.value || '0');
  
  if (newExpense.value.splitType === 'money') {
    const diff = Math.abs(total - newExpense.value.totalCost);
    if (diff >= 0.01) {
      splitError.value = `Total must equal $${newExpense.value.totalCost.toFixed(2)}. Current: $${total.toFixed(2)}`;
    }
  } else {
    const diff = Math.abs(total - 100);
    if (diff >= 0.1) {
      splitError.value = `Total must equal 100%. Current: ${total.toFixed(1)}%`;
    }
  }
}

// Reset custom splits when splitBetween changes
watch(() => newExpense.value.splitBetween, () => {
  if (showAdvancedSettings.value) {
    customSplits.value = {};
    splitError.value = '';
  }
});

function addExpense() {
  if (newExpense.value.splitBetween.length === 0) {
    alert('Please select at least one person to split with');
    return;
  }

  if (showAdvancedSettings.value && !isSplitValid.value) {
    alert('Please fix the split amounts before submitting');
    return;
  }

  // Calculate split amounts
  let splitBetween;
  if (showAdvancedSettings.value) {
    // Use custom splits
    splitBetween = newExpense.value.splitBetween.map(userId => ({
      userId,
      cost: newExpense.value.splitType === 'money' ? (customSplits.value[userId] || 0) : undefined,
      percentage: newExpense.value.splitType === 'percentage' ? (customSplits.value[userId] || 0) : undefined,
    }));
  } else {
    // Equal split
    const splitAmount = newExpense.value.totalCost / newExpense.value.splitBetween.length;
    splitBetween = newExpense.value.splitBetween.map(userId => ({
      userId,
      cost: newExpense.value.splitType === 'money' ? splitAmount : undefined,
      percentage: newExpense.value.splitType === 'percentage' ? 100 / newExpense.value.splitBetween.length : undefined,
    }));
  }

  const expense: Expense = {
    id: Date.now().toString(),
    title: newExpense.value.title,
    totalCost: newExpense.value.totalCost,
    paidBy: newExpense.value.paidBy,
    splitBetween,
    date: new Date().toISOString().split('T')[0],
    splitType: newExpense.value.splitType,
  };

  emit('add-expense', expense);
  showAddExpenseDialog.value = false;
  showAdvancedSettings.value = false;
  customSplits.value = {};
  splitError.value = '';
  newExpense.value = {
    title: '',
    totalCost: 0,
    paidBy: '',
    splitBetween: [],
    splitType: 'money',
  };
}
</script>

<style scoped>
.costs-tab {
  width: 100%;
}

.space-y-6 > * + * {
  margin-top: 1.5rem;
}

.costs-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(400px, 1fr));
  gap: 1.5rem;
}

.card {
  position: relative;
  background: white;
  border-radius: 1rem;
  overflow: hidden;
  box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
  border: 0;
}

.card-gradient-gold {
  height: 6px;
  background: #f4c542;
}

.card-header {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  padding: 1.5rem;
  padding-bottom: 1rem;
}

.card-title {
  font-size: 1.125rem;
  font-weight: 600;
  color: #1e3a5f;
  margin-bottom: 0.25rem;
}

.card-description {
  font-size: 0.875rem;
  color: #64748b;
}

.card-content {
  padding: 0 1.5rem 1.5rem 1.5rem;
}

.btn-add-expense {
  display: flex;
  align-items: center;
  padding: 0.5rem 1rem;
  background: #f4c542;
  color: #1e3a5f;
  border: none;
  border-radius: 9999px;
  font-size: 0.875rem;
  font-weight: 500;
  cursor: pointer;
  transition: all 0.2s;
  box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1);
}

.btn-add-expense:hover {
  background: #e0b138;
  box-shadow: 0 4px 6px -1px rgba(0, 0, 0, 0.1);
  transform: scale(1.05);
}

.w-4 {
  width: 1rem;
}

.h-4 {
  height: 1rem;
}

.mr-2 {
  margin-right: 0.5rem;
}

.text-green-600 {
  color: #16a34a;
}

.text-red-500 {
  color: #ef4444;
}

.balances-list {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.balance-item {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  padding: 0.75rem;
  background: #f9fafb;
  border-radius: 0.5rem;
}

.balance-avatar {
  width: 2.5rem;
  height: 2.5rem;
  border-radius: 50%;
  color: white;
  display: flex;
  align-items: center;
  justify-content: center;
  font-weight: 600;
  font-size: 0.875rem;
  box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1);
}

.balance-info {
  flex: 1;
}

.balance-name {
  font-weight: 500;
  color: #1e3a5f;
}

.balance-amount-wrapper {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.balance-amount {
  display: flex;
  align-items: center;
  gap: 0.25rem;
  font-size: 1rem;
  font-weight: 600;
}

.balance-amount.positive {
  color: #16a34a;
}

.balance-amount.negative {
  color: #dc2626;
}

.badge-settled {
  font-size: 0.75rem;
  background: #f1f5f9;
  color: #64748b;
  padding: 0.25rem 0.75rem;
  border-radius: 9999px;
}

.expenses-list {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
}

.empty-state {
  text-align: center;
  padding: 2rem;
  color: #64748b;
}

.expense-item {
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
  padding: 0.75rem;
  background: #f9fafb;
  border-radius: 0.5rem;
  transition: all 0.2s;
  position: relative;
}

.expense-item:hover {
  box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.1);
}

.expense-info {
  flex: 1;
}

.expense-header {
  display: flex;
  align-items: center;
  gap: 0.5rem;
  margin-bottom: 0.25rem;
}

.expense-header h3 {
  font-size: 0.875rem;
  font-weight: 500;
  color: #1e3a5f;
}

.expense-details {
  font-size: 0.875rem;
  color: #64748b;
  margin-bottom: 0.25rem;
}

.expense-per-person {
  font-size: 0.75rem;
  color: #94a3b8;
}

.expense-amount-wrapper {
  display: flex;
  align-items: center;
  gap: 0.5rem;
}

.expense-amount {
  font-size: 1.125rem;
  font-weight: 600;
  color: #1e3a5f;
}

.btn-delete-expense {
  background: transparent;
  border: none;
  cursor: pointer;
  opacity: 0;
  transition: opacity 0.2s;
  padding: 0.25rem;
}

.expense-item:hover .btn-delete-expense {
  opacity: 1;
}

.btn-primary {
  background: #42b983;
  color: white;
  border: none;
  padding: 0.5rem 1rem;
  border-radius: 6px;
  font-size: 0.9rem;
  font-weight: 500;
  cursor: pointer;
  transition: background 0.2s;
}

.btn-primary:hover {
  background: #35a372;
}

.btn-secondary {
  background: #f0f0f0;
  color: #333;
  border: none;
  padding: 0.5rem 1rem;
  border-radius: 6px;
  font-size: 0.9rem;
  font-weight: 500;
  cursor: pointer;
  transition: background 0.2s;
}

.btn-secondary:hover {
  background: #e0e0e0;
}

.dialog-overlay {
  position: fixed;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  background: rgba(0, 0, 0, 0.5);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
}

.dialog {
  background: white;
  border-radius: 12px;
  padding: 2rem;
  width: 90%;
  max-width: 500px;
  max-height: 90vh;
  overflow-y: auto;
}

.dialog h2 {
  margin-bottom: 1.5rem;
  color: #333;
}

.form-group {
  margin-bottom: 1.5rem;
}

.form-group label {
  display: block;
  margin-bottom: 0.5rem;
  color: #333;
  font-weight: 500;
}

.form-group input,
.form-group select {
  width: 100%;
  padding: 0.75rem;
  border: 1px solid #ddd;
  border-radius: 8px;
  font-size: 1rem;
}

.checkbox-group {
  display: flex;
  flex-direction: column;
  gap: 0.75rem;
  margin-top: 0.5rem;
}

.checkbox-label {
  display: flex;
  align-items: center;
  gap: 0.75rem;
  font-weight: normal;
  cursor: pointer;
}

.checkbox-label input[type="checkbox"] {
  width: 20px;
  height: 20px;
  cursor: pointer;
}

.form-actions {
  display: flex;
  gap: 1rem;
  justify-content: flex-end;
  margin-top: 2rem;
}

.btn-link {
  background: none;
  border: none;
  color: #42b983;
  font-size: 0.9rem;
  font-weight: 500;
  cursor: pointer;
  padding: 0.5rem 0;
  text-align: left;
  transition: color 0.2s;
}

.btn-link:hover {
  color: #35a372;
}

.advanced-settings {
  background: #f9f9f9;
  padding: 1.5rem;
  border-radius: 8px;
  margin-top: 1rem;
  border: 1px solid #e0e0e0;
}

.help-text {
  font-size: 0.85rem;
  color: #666;
  margin-bottom: 1rem;
}

.custom-splits {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.custom-split-item {
  display: flex;
  align-items: center;
  gap: 1rem;
}

.split-label {
  min-width: 120px;
  font-weight: 500;
  color: #333;
  font-size: 0.9rem;
}

.split-input {
  flex: 1;
  padding: 0.5rem;
  border: 1px solid #ddd;
  border-radius: 6px;
  font-size: 1rem;
}

.split-total {
  margin-top: 1rem;
  padding-top: 1rem;
  border-top: 1px solid #e0e0e0;
  font-weight: 600;
  color: #333;
}

.split-total .valid {
  color: #42b983;
}

.split-total .invalid {
  color: #ff9800;
}

.error-message {
  background: #fee;
  color: #c33;
  padding: 0.75rem;
  border-radius: 8px;
  font-size: 0.9rem;
  border: 1px solid #fcc;
  margin-top: 1rem;
}

.btn-primary:disabled {
  background: #ccc;
  cursor: not-allowed;
}
</style>
